
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button btnExec;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TextView txtXpath;
	
	private global::Gtk.ComboBox cbbType;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView txtSource;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView txtResult;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(1));
		this.table1.ColumnSpacing = ((uint)(1));
		this.table1.BorderWidth = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 5;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnExec = new global::Gtk.Button ();
		this.btnExec.WidthRequest = 150;
		this.btnExec.CanFocus = true;
		this.btnExec.Name = "btnExec";
		this.btnExec.UseUnderline = true;
		this.btnExec.Label = global::Mono.Unix.Catalog.GetString ("确定(_O)");
		global::Gtk.Image w1 = new global::Gtk.Image ();
		w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-jump-to", global::Gtk.IconSize.Menu);
		this.btnExec.Image = w1;
		this.hbox1.Add (this.btnExec);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnExec]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.txtXpath = new global::Gtk.TextView ();
		this.txtXpath.Buffer.Text = "\n88888";
		this.txtXpath.CanFocus = true;
		this.txtXpath.Name = "txtXpath";
		this.GtkScrolledWindow2.Add (this.txtXpath);
		this.hbox1.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow2]));
		w4.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbbType = global::Gtk.ComboBox.NewText ();
		this.cbbType.AppendText (global::Mono.Unix.Catalog.GetString ("HTML"));
		this.cbbType.AppendText (global::Mono.Unix.Catalog.GetString ("XML"));
		this.cbbType.Name = "cbbType";
		this.cbbType.Active = 0;
		this.hbox1.Add (this.cbbType);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbbType]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.table1.Add (this.hbox1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
		this.table2.HeightRequest = 550;
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(1));
		this.table2.ColumnSpacing = ((uint)(1));
		// Container child table2.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtSource = new global::Gtk.TextView ();
		this.txtSource.CanFocus = true;
		this.txtSource.Name = "txtSource";
		this.GtkScrolledWindow.Add (this.txtSource);
		this.table2.Add (this.GtkScrolledWindow);
		// Container child table2.Gtk.Table+TableChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtResult = new global::Gtk.TextView ();
		this.txtResult.CanFocus = true;
		this.txtResult.Name = "txtResult";
		this.txtResult.Editable = false;
		this.GtkScrolledWindow1.Add (this.txtResult);
		this.table2.Add (this.GtkScrolledWindow1);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow1]));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		this.table1.Add (this.table2);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.table2]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 899;
		this.DefaultHeight = 622;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnExec.Clicked += new global::System.EventHandler (this.OnBtnExecClicked);
	}
}
